//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Koristi
    {
        public int RadnikSaAlatomIdRad { get; set; }
        public int AlatSrBrAl { get; set; }
    
        public virtual RadnikSaAlatom RadnikSaAlatom { get; set; }
        public virtual Alat Alat { get; set; }
    }
}
