//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDBContext : DbContext
    {
        public ModelDBContext()
            : base("name=ModelDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Radnik> RadnikSet { get; set; }
        public virtual DbSet<Priprema> PripremaSet { get; set; }
        public virtual DbSet<Proizvodnja> ProizvodnjaSet { get; set; }
        public virtual DbSet<Materijal> MaterijalSet { get; set; }
        public virtual DbSet<Traka> TrakaSet { get; set; }
        public virtual DbSet<Masina> MasinaSet { get; set; }
        public virtual DbSet<Alat> AlatSet { get; set; }
        public virtual DbSet<Odnosi> OdnosiSet { get; set; }
        public virtual DbSet<Obucava> ObucavaSet { get; set; }
        public virtual DbSet<Kontrolise> KontroliseSet { get; set; }
        public virtual DbSet<Koristi> KoristiSet { get; set; }
        public virtual DbSet<Upotrebljava> UpotrebljavaSet { get; set; }
        public virtual DbSet<Podesava> PodesavaSet { get; set; }
        public virtual DbSet<GotovProizvod> GotovProizvodSet { get; set; }
    }
}
