//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odnosi
    {
        public int KolMat { get; set; }
        public int MagacionerIdRad { get; set; }
        public int MaterijalOznMat { get; set; }
    
        public virtual Magacioner Magacioner { get; set; }
        public virtual Materijal Materijal { get; set; }
    }
}
