//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podesava
    {
        public int NormerIdRad { get; set; }
        public int TrakaOznTr { get; set; }
        public int BrzTr { get; set; }
    
        public virtual Normer Normer { get; set; }
        public virtual Traka Traka { get; set; }
    }
}
