//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SefProizvodnje : Sef
    {
        public Nullable<int> ProizvodnjaOznProiz { get; set; }
    
        public virtual Proizvodnja Proizvodnja { get; set; }
    }
}
