//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    
    public enum TipRadnika : int
    {
        DIREKTOR = 0,
        SEF = 1,
        NORMER = 2,
        MAGACIONER = 3,
        MAJSTORICA = 4,
        RADNIKNATRACI = 5
    }
}
