//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatBaze2
{
    using System;
    
    public enum TipRadnika : int
    {
        Direktor = 0,
        Sef = 1,
        Normer = 2,
        Magacioner = 3,
        Majstorica = 4,
        RadnikNaTraci = 5
    }
}
